# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2
updates:
  # Maintain dependencies for GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/.github"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 5

  # Maintain dependencies for nuget src
  - package-ecosystem: "nuget"
    directory: "/src"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 16
    ignore:
      - dependency-name: "Microsoft.AspNetCore.*"
        versions: ["7.*"]
      - dependency-name: "Microsoft.EntityFrameworkCore"
        versions: ["7.*"]
      - dependency-name: "Microsoft.EntityFrameworkCore.*"
        versions: ["7.*"]
      - dependency-name: "Microsoft.VisualStudio.*"
        versions: ["7.*"]

  # Maintain dependencies for nuget tests
  - package-ecosystem: "nuget"
    directory: "/tests"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 16
    ignore:
      - dependency-name: "Microsoft.AspNetCore.*"
        versions: ["7.*"]
      - dependency-name: "Microsoft.EntityFrameworkCore"
        versions: ["7.*"]
      - dependency-name: "Microsoft.EntityFrameworkCore.*"
        versions: ["7.*"]
      - dependency-name: "Microsoft.Data.*"
        versions: ["7.*"]
      - dependency-name: "Microsoft.VisualStudio.*"
        versions: ["7.*"]

  # Maintain dependencies for docker
  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 8
    ignore:
      - dependency-name: "*"
        versions: ["7.0-alpine"]


