version: "3"

services:
  mssql:
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=${MSSQL_PASSWD:?Need to set MSSQL_PASSWD}
    ports:
      - "1433:1433"
    volumes:
      - mssqlvol:/var/opt/mssql 
  cysim:
    build: ./ #https://github.com/BHeinen/CySim.git
    ports:
      - "8080:80"
    depends_on:
      - mssql
    environment:
      - ASPNETCORE_ENVIRONMENT=${ENV}
      - ConnectionStrings__Default=Server=mssql;Database=CySim;User Id=sa;Password=${MSSQL_PASSWD};Trusted_Connection=True;MultipleActiveResultSets=true;Integrated Security=False
    entrypoint:
      - dotnet 
      - CySim.dll
volumes:
  mssqlvol:
