version: "3"

services:
  # Test that the mssql service is running
  mssql:
    healthcheck:
      test: /opt/mssql-tools/bin/sqlcmd -S localhost -U sa -P "$$MSSQL_SA_PASSWORD" -Q "SELECT 1" || exit 1
      interval: 60s
      retries: 10
      start_period: 10s
      timeout: 3s

  # Curl the webpage to check that it is running
  cysim:
    healthcheck:
      test: curl --fail http://localhost || exit 1
      interval: 60s
      retries: 3
      start_period: 10s
      timeout: 5s



# Integration tests and dotnet unit test service will be added below 

