name: "Zap-Baseline"

on:
  push:
    branches: [ "master" ]
  pull_request:
    # The branches below must be a subset of the branches above
    branches: [ "master" ]

jobs:
  zap_scan:
    runs-on: ubuntu-latest
    name: Scan the webapplication
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      
      - name: Add MSSQL Password
        run: echo "MSSQL_PASSWD=$(openssl rand -base64 24)" >> .env
      
      - name: Docker Run
        run: docker compose up -d
        
      - name: ZAP Scan
        uses: zaproxy/action-baseline@v0.7.0
        with:
          cmd_options: '--network=main'
          target: 'http://cysim'
